#  ETL-Pipeline

In [1]:
import sqlalchemy
import pymysql

In [2]:
import pandas as pd
import requests
from datetime import datetime, timedelta
from bs4 import BeautifulSoup
from lat_lon_parser import parse
import os
from dotenv import load_dotenv

## Web Scrapping for City Data

In [3]:
# First look at the data from Berlin alone
url = "https://en.wikipedia.org/wiki/Berlin"
headers = {'User-Agent': 'Chrome/134.0.0.0'}

response = requests.get(url, headers=headers)

soup_Berlin = BeautifulSoup(response.content, 'html.parser')

In [4]:
# exploring the data
soup_Berlin.prettify()

'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <title>\n   Berlin - Wikipedia\n  </title>\n  <script>\n   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"81b31802-6871-48ad-accc-ca1fa8b833f7","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Berlin","wgTitle":"Berlin","wgCurRevisionId":1376294941,"wgRevisionId":1376294941,"wgArticleId":3354,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use dmy dates from August 2024","Use American English from August 2024","All Wikipedia articles written in American English","Pages using gadget WikiMiniAtlas","CS1 German-language sources (de)","Pages using infobox settlement with bad settlement type","Pages using multiple image with auto scaled images","Coordinates on Wikidata","Articles containing German-language text","Pages using the Phonos extension","Pages including recorded pronunciations","Pages with German IPA","Articles containing Polabian-language text","Webarchive template wayback links","Wikipedia articles needing clarification from August 2026","CS1 maint: deprecated archival service","Articles containing potentially dated statements from 2019","All articles containing potentially dated statements","CS1: unfit URL","All articles with unsourced statements","Articles with unsourced statements from May 2024","Articles containing potentially dated statements from 2014","CS1 French-language sources (fr)","Articles containing potentially dated statements from 2011","Articles containing potentially dated statements from August 2024","Wikipedia articles incorporating a citation from the 1911 Encyclopaedia Britannica with Wikisource reference","Pages using the Kartographer extension","Berlin","German state capitals","East Germany (Region)","Capital cities in Europe","City-states","Members of the Hanseatic League","Populated places established in the 13th century","Turkish communities outside Turkey","1230s establishments in the Holy Roman Empire","1237 establishments in Europe","States of Germany","NUTS 2 statistical regions of Germany","NUTS 3 statistical regions of the European Union","Holocaust locations in Germany","Subnational enclaves and exclaves"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Berlin","wgRelevantArticleId":3354,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":200000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgCoordinates":{"lat":52.519999999999996,"lon":13.405000000000001},"wgPageAssessments":{"Cities":{"class":"B","importance":""},"Cities/Core":{"class":"B","importance":""},"Cities/National capitals":{"class":"B","importance":""},"Former countries":{"class":"B","importance":""},"Former countries/Holy Roman Empire task force":{"class":"B","importance":"Unknown"},"Former countries/WikiProject Prussia":{"class":"B","importance":""},"Geography":{"class":"B","importance":"High"},"Germany":{"class":"B","importance":"Top"},"Hanseatic League":{"class":"B","importance":""},"Middle Ages":{"class":"B","importance":"Mid"},"Middle Ages/WikiProject History":{"class":"B","importance":""},"Olympics":{"class":"B","importance":"Low"},"Project-independent assessment":{"class":"B","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q64","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.phonos.styles":"ready","ext.phonos.icons":"ready","mediawiki.page.gallery.styles":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","ext.kartographer.style":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready","ext.wikimediaBadges.ulsV2":"ready"};RLPAGEMODULES=["ext.kartographer.staticframe","ext.phonos.init","ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.gadget.WikiMiniAtlas","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];\n  </script>\n  <script>\n   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});mw.user.options.set({"usecodemirror":1});\n}];});});\n  </script>\n  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.kartographer.style%7Cext.phonos.icons%2Cstyles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediaBadges.ulsV2%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cmediawiki.page.gallery.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>\n  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">\n  </script>\n  <meta content="" name="ResourceLoaderDynamicStyles"/>\n  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>\n  <meta content="MediaWiki 1.47.0-wmf.21" name="generator"/>\n  <meta content="origin" name="referrer"/>\n  <meta content="origin-when-cross-origin" name="referrer"/>\n  <meta content="max-image-preview:standard" name="robots"/>\n  <meta content="telephone=no" name="format-detection"/>\n  <meta content="https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg/1280px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29_b.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>\n  <meta content="1200" property="og:image:width"/>\n  <meta content="700" property="og:image:height"/>\n  <meta content="width=1120" name="viewport"/>\n  <meta content="Berlin - Wikipedia" property="og:title"/>\n  <meta content="website" property="og:type"/>\n  <link href="//thumb.wikimedia.org" rel="preconnect"/>\n  <link href="/w/index.php?title=Berlin&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>\n  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>\n  <link href="/static/favicon/wikipedia.ico" rel="icon"/>\n  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>\n  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>\n  <link href="https://en.wikipedia.org/wiki/Berlin" rel="canonical"/>\n  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>\n  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>\n  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>\n  <link href="auth.wikimedia.org" rel="dns-prefetch"/>\n </head>\n <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Berlin rootpage-Berlin skin-vector-2022 action-view">\n  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">\n  </div>\n  <a class="mw-jump-link" href="#bodyContent">\n   Jump to content\n  </a>\n  <div class="vector-header-container">\n   <header class="vector-header mw-header no-font-mode-scale">\n    <div class="vector-header-start">\n     <nav aria-label="Site" class="vector-main-menu-landmark">\n      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">\n       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>\n       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">\n        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">\n        </span>\n        <span class="vector-dropdown-label-text">\n         Main menu\n        </span>\n       </label>\n       <div class="vector-dropdown-content">\n        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">\n         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">\n          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">\n           <div class="vector-pinnable-header-label">\n            Main menu\n           </div>\n           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">\n            move to sidebar\n           </button>\n           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">\n            hide\n           </button>\n          </div>\n          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">\n           <div class="vector-menu-heading">\n            Navigation\n           </div>\n           <div class="vector-menu-content">\n            <ul class="vector-menu-content-list">\n             <li class="mw-list-item" id="n-mainpage-description">\n              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">\n               <span>\n                Main page\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-contents">\n              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">\n               <span>\n                Contents\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-currentevents">\n              <a href="/wiki/Portal:Current_events" title="Articles related to current events">\n               <span>\n                Current events\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-randompage">\n              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">\n               <span>\n                Random article\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-aboutsite">\n              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">\n               <span>\n                About Wikipedia\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-contactpage">\n              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">\n               <span>\n                Contact us\n               </span>\n              </a>\n             </li>\n            </ul>\n           </div>\n          </div>\n          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">\n           <div class="vector-menu-heading">\n            Contribute\n           </div>\n           <div class="vector-menu-content">\n            <ul class="vector-menu-content-list">\n             <li class="mw-list-item" id="n-help">\n              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">\n               <span>\n                Help\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-introduction">\n              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">\n               <span>\n                Learn to edit\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-portal">\n              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">\n               <span>\n                Community portal\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-recentchanges">\n              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">\n               <span>\n                Recent changes\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-upload">\n              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">\n               <span>\n                Upload file\n               </span>\n              </a>\n             </li>\n             <li class="mw-list-item" id="n-specialpages">\n              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">\n               <span>\n                Special pages\n               </span>\n              </a>\n             </li>\n            </ul>\n           </div>\n          </div>\n         </div>\n        </div>\n       </div>\n      </div>\n     </nav>\n     <a class="mw-logo" href="/wiki/Main_Page">\n      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>\n      <span class="mw-logo-container skin-invert">\n       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>\n       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>\n      </span>\n     </a>\n    </div>\n    <div class="vector-header-end">\n     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">\n      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">\n       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">\n       </span>\n       <span>\n        Search\n       </span>\n      </a>\n      <div class="vector-typeahead-search-container">\n       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">\n         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">\n          <div class="cdx-text-input cdx-text-input--has-start-icon">\n           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>\n           <span class="cdx-text-input__icon cdx-text-input__start-icon">\n           </span>\n          </div>\n          <input name="title" type="hidden" value="Special:Search"/>\n         </div>\n         <button class="cdx-button cdx-search-input__end-button">\n          Search\n         </button>\n        </form>\n       </div>\n      </div>\n     </div>\n     <nav aria-label="Personal tools" class

In [5]:
# looking at the infobox
soup_Berlin.find_all(class_="infobox-data")

[<td class="infobox-data"><span class="flagicon nowrap"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="1000" decoding="async" height="14" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Germany.svg" src="//thumb.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/40px-Flag_of_Germany.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/60px-Flag_of_Germany.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></span></span> </span><a href="https://en.wikipedia.org/wiki/Germany" rel="mw:WikiLink" title="Germany">Germany</a></td>,
 <td class="infobox-data"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Boroughs_and_neighborhoods_of_Berlin" rel="mw:WikiLink" title="Boroughs and neighborhoods of Berlin">Berlin</a></td>,
 <td class="infobox-data agent"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Abgeordnetenhaus_of_Berlin" rel="mw:WikiLink" title="Abgeordnetenhaus of Berlin">Abgeordnetenhaus of Berlin</a></td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/Kai_Wegner" rel="mw:WikiLink" title="Kai Wegner">Kai Wegner</a> (CDU)</td>,
 <td class="infobox-data">4 (of 69)</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/Results_of_the_2025_German_federal_election#Berlin" rel="mw:WikiLink" title="Results of the 2025 German federal election">24 (of 630)</a> <small>(as of 2025)</small></td>,
 <td class="infobox-data">891.3<span typeof="mw:Entity"> </span>km<sup>2</sup> (344.1<span typeof="mw:Entity"> </span>sq<span typeof="mw:Entity"> </span>mi)</td>,
 <td class="infobox-data">3,743<span typeof="mw:Entity"> </span>km<sup>2</sup> (1,445<span typeof="mw:Entity"> </span>sq<span typeof="mw:Entity"> </span>mi)</td>,
 <td class="infobox-data">34<span typeof="mw:Entity"> </span>m (112<span typeof="mw:Entity"> </span>ft)</td>,
 <td class="infobox-data">3,596,999</td>,
 <td class="infobox-data">3,700,577</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/List_of_European_cities_by_population_within_city_limits" rel="mw:WikiLink" title="List of European cities by population within city limits">5th</a> in Europe<br/><a href="https://en.wikipedia.org/wiki/List_of_cities_in_Germany_by_population" rel="mw:WikiLink" title="List of cities in Germany by population">1st</a> in Germany</td>,
 <td class="infobox-data">4,109/km<sup>2</sup> (10,640/sq<span typeof="mw:Entity"> </span>mi)</td>,
 <td class="infobox-data">4,679,500</td>,
 <td class="infobox-data">1,250/km<sup>2</sup> (3,200/sq<span typeof="mw:Entity"> </span>mi)</td>,
 <td class="infobox-data">Berliner(s) (English)<br/><span title="German-language text"><i lang="de">Berliner</i></span><link href="./Category:Articles_containing_German-language_text" rel="mw:PageProp/Category"/> (m), <span title="German-language text"><i lang="de">Berlinerin</i></span><link href="./Category:Articles_containing_German-language_text" rel="mw:PageProp/Category"/> (f) (German)</td>,
 <td class="infobox-data">€218.29 <a href="https://en.wikipedia.org/wiki/1,000,000,000" rel="mw:WikiLink" title="1,000,000,000">billion</a><span typeof="mw:Entity"> </span>(<a href="https://en.wikipedia.org/wiki/United_States_dollar" rel="mw:WikiLink" title="United States dollar">US$</a>258.17 <a href="https://en.wikipedia.org/wiki/1,000,000,000" rel="mw:WikiLink" title="1,000,000,000">billion</a>)</td>,
 <td class="infobox-data">€322.39 <a href="https://en.wikipedia.org/wiki/1,000,000,000" rel="mw:WikiLink" title="1,000,000,000">billion</a><span typeof="mw:Entity"> </span>(<a href="https://en.wikipedia.org/wiki/United_States_dollar" rel="mw:WikiLink" title="United States dollar">US$</a>381.29 <a href="https://en.wikipedia.org/wiki/1,000,000,000" rel="mw:WikiLink" title="1,000,000,000">billion</a>)</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/UTC+01:00" rel="mw:WikiLink" title="UTC+01:00">UTC+01:00</a> (<a href="https://en.wikipedia.org/wiki/Central_European_Time" rel="mw:WikiLink" title="Central European Time">CET</a>)</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/UTC+02:00" rel="mw:WikiLink" title="UTC+02:00">UTC+02:00</a> (<a href="https://en.wikipedia.org/wiki/Central_European_Summer_Time" rel="mw:WikiLink" title="Central European Summer Time">CEST</a>)</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Germany#030_–_Berlin" rel="mw:WikiLink" title="List of dialling codes in Germany">030</a><span data-plural="0" style="display:none"></span></td>,
 <td class="infobox-data nickname"><a href="https://en.wikipedia.org/wiki/Nomenclature_of_Territorial_Units_for_Statistics" rel="mw:WikiLink" title="Nomenclature of Territorial Units for Statistics">NUTS Region</a>: DE3</td>,
 <td class="infobox-data nickname">DE-BE</td>,
 <td class="infobox-data">B</td>,
 <td class="infobox-data"><a href="https://en.wikipedia.org/wiki/.berlin" rel="mw:WikiLink" title=".berlin">.berlin</a></td>,
 <td class="infobox-data">0.967<sup about="#mwt47" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwIw"><span class="mw-reflink-text" id="mwJA"><span class="cite-bracket" id="mwJQ">[</span>6<span class="cite-bracket" id="mwJg">]</span></span></a></sup><br/><style about="#mwt50" data-mw='{"name":"templatestyles","attrs":{"src":"Template:Color/styles.css"}}' data-mw-deduplicate="TemplateStyles:r1239334494" typeof="mw:Extension/templatestyles">@media screen{html.skin-theme-clientpref-night .mw-parser-output div:not(.notheme)>.tmp-color,html.skin-theme-clientpref-night .mw-parser-output p>.tmp-color,html.skin-theme-clientpref-night .mw-parser-output table:not(.notheme) .tmp-color{color:inherit!important}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output div:not(.notheme)>.tmp-color,html.skin-theme-clientpref-os .mw-parser-output p>.tmp-color,html.skin-theme-clientpref-os .mw-parser-output table:not(.notheme) .tmp-color{color:inherit!important}}</style><span class="tmp-color" style="color:green">very high</span> · <a href="https://en.wikipedia.org/wiki/List_of_German_states_by_Human_Development_Index" rel="mw:WikiLink" title="List of German states by Human Development Index">2nd of 16</a></td>,
 <td class="infobox-data"><span class="url"><a class="external text" href="https://www.berlin.de/en/" rel="mw:ExtLink nofollow">berlin.de</a></span></td>]

In [6]:
# get country from infobox
soup_Berlin.find(class_="infobox-data").get_text()

' Germany'

In [7]:
berlin_country = soup_Berlin.find(class_="infobox-data").get_text()
berlin_country

' Germany'

In [8]:
# Berlin Latitude
berlin_latitude = soup_Berlin.find(class_="latitude").get_text()
berlin_latitude

'52°31′12″N'

In [9]:
# Berlin Longitude
berlin_longitude = soup_Berlin.find(class_="longitude").get_text()
berlin_longitude

'13°24′18″E'

Second city Hamburg

In [10]:
url = 'https://www.wikipedia.org/wiki/Hamburg'
headers = {'User-Agent': 'Chrome/139.0.0.0'}

response = requests.get(url, headers=headers)
hamburg_soup = BeautifulSoup(response.content, 'html.parser')

hamburg_country = hamburg_soup.find(class_="infobox-data").get_text()
hamburg_latitude = hamburg_soup.find(class_="latitude").get_text()
hamburg_longitude = hamburg_soup.find(class_="longitude").get_text()

hamburg_country, hamburg_latitude, hamburg_longitude

(' Germany', '53°33′N', '10°00′E')

Third city Cologne

In [11]:
url = 'https://en.wikipedia.org/wiki/Cologne'
headers = {'User-Agent': 'Chrome/139.0.0.0'}

response = requests.get(url, headers=headers)
cologne_soup = BeautifulSoup(response.content, 'html.parser')

cologne_country = cologne_soup.find(class_="infobox-data").get_text()
cologne_latitude = cologne_soup.find(class_="latitude").get_text()
cologne_longitude = cologne_soup.find(class_="longitude").get_text()

cologne_country, cologne_latitude, cologne_longitude

('Germany', '50°56′11″N', '6°57′10″E')

Get all city data with a for loop

In [12]:
cities = ["Berlin", "Hamburg", "Cologne"]

countries = []
latitudes = []
longitudes = []

for city in cities:
  # get the soup for the city
  url = f"https://www.wikipedia.org/wiki/{city}"
  headers = {'User-Agent': 'Chrome/134.0.0.0'}

  response = requests.get(url, headers=headers)
  city_soup = BeautifulSoup(response.content, 'html.parser')

  # extract the data
  city_country = city_soup.find(class_="infobox-data").get_text()
  city_latitude = city_soup.find(class_="latitude").get_text()
  city_longitude = city_soup.find(class_="longitude").get_text()

  # append data to a list
  countries.append(city_country)
  latitudes.append(city_latitude)
  longitudes.append(city_longitude)

In [13]:
print(f"The cities are in the following countries: {countries}")
print(f"The cities have the following latitudes: {latitudes}")
print(f"The cities have the following longitudes: {longitudes}")

The cities are in the following countries: [' Germany', ' Germany', 'Germany']
The cities have the following latitudes: ['52°31′12″N', '53°33′N', '50°56′11″N']
The cities have the following longitudes: ['13°24′18″E', '10°00′E', '6°57′10″E']

Creating a DataFrame

In [14]:
cities_df = pd.DataFrame({"City": cities,
                          "Country": countries,
                          "Latitude": latitudes,
                          "Longitude": longitudes})

cities_df

      City   Country    Latitude   Longitude
0   Berlin   Germany  52°31′12″N  13°24′18″E
1  Hamburg   Germany     53°33′N     10°00′E
2  Cologne   Germany  50°56′11″N   6°57′10″E

For easier analysis parse the latitude and longitude

In [15]:
# example
parse(berlin_latitude)

52.519999999999996

Create a function to easily gather city data

In [16]:
def cities_dataframe(cities):

  city_data = []

  for city in cities:
    url = f"https://www.wikipedia.org/wiki/{city}"
    headers = {'User-Agent': 'Chrome/134.0.0.0'}

    response = requests.get(url, headers=headers)
    city_soup = BeautifulSoup(response.content, 'html.parser')

    # extract the relevant information
    city_latitude = city_soup.find(class_="latitude").get_text()
    city_longitude = city_soup.find(class_="longitude").get_text()
    country = city_soup.find(class_="infobox-data").get_text()

    # keep track of data per city
    city_data.append({"City": city,
                    "Country": country,
                    "Latitude": parse(city_latitude), # latitude in decimal format
                    "Longitude": parse(city_longitude), # longitude in decimal format
                    })

  return pd.DataFrame(city_data)

In [17]:
# call the function
list_of_cities = ["Berlin", "Hamburg", "Cologne"]

cities_df = cities_dataframe(list_of_cities)
cities_df

      City   Country   Latitude  Longitude
0   Berlin   Germany  52.520000  13.405000
1  Hamburg   Germany  53.550000  10.000000
2  Cologne   Germany  50.936389   6.952778

Gather city population

In [18]:
# search for the number for population
soup_Berlin.find(string="Population").find_next()
# The number for population is not next to the word "Population" on Wikipedia, need to refine the search.

<div class="ib-settlement-fn"><span class="nowrap"><span typeof="mw:Entity"> </span></span>(2022 census)<sup about="#mwt26" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-2"}}' id="cite_ref-2" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-2" id="mwEw"><span class="mw-reflink-text" id="mwFA"><span class="cite-bracket" id="mwFQ">[</span>2<span class="cite-bracket" id="mwFg">]</span></span></a></sup></div>

In [19]:
# finding the number
soup_Berlin.find(string="Population").find_next("td")

In [20]:
# get string for population number
berlin_population = soup_Berlin.find(string="Population").find_next("td").get_text()
berlin_population

'3,596,999'

In [21]:
# remove commas from the number
berlin_population_clean = berlin_population.replace(",", "")
berlin_population_clean

'3596999'

In [22]:
# turn the number into an integer
berlin_population_clean = int(berlin_population_clean)
berlin_population_clean

3596999

In [23]:
cities = ["Berlin", "Hamburg", "Cologne"]

# create one single list to keep track of all values (instead of having separate lists)
population_data = []

for city in cities:
    url = f"https://www.wikipedia.org/wiki/{city}"
    headers = {'User-Agent': 'Chrome/134.0.0.0'}

    response = requests.get(url, headers=headers)
    city_soup = BeautifulSoup(response.content, 'html.parser')

    # extract the relevant information
    city_population = city_soup.find(string="Population").find_next("td").get_text()
    city_population_clean = city_population.replace(",", "")
    today = datetime.today().strftime("%d.%m.%Y")

    # for each city we append a dictionary of values to the list
    population_data.append({"City": city,
                     "population": int(city_population_clean),
                     "population_Timestamp": today
                    })

population_data = pd.DataFrame(population_data)
population_data

      City  population population_Timestamp
0   Berlin     3596999           26.09.2026
1  Hamburg     1973896           26.09.2026
2  Cologne     1025523           26.09.2026

In [24]:
# Gather population from cities function:

def populations_dataframe(cities):

    population_data = []

    for city in cities:
        url = f"https://www.wikipedia.org/wiki/{city}"
        headers = {'User-Agent': 'Chrome/134.0.0.0'}

        response = requests.get(url, headers=headers)
        city_soup = BeautifulSoup(response.content, 'html.parser')

        # extract the relevant information
        city_population = city_soup.find(string="Population").find_next("td").get_text()
        city_population_clean = int(city_population.replace(",", ""))
        today = datetime.today().strftime("%Y-%m-%d")

        # keep track of data per city
        population_data.append({"population": city_population_clean,
                        "timestamp_population": today
                        })

    return pd.DataFrame(population_data)

In [25]:
# call the populations function
cities = ["Berlin", "Cologne", "Hamburg"]

population_df = populations_dataframe(cities)
population_df

   population timestamp_population
0     3596999           2026-09-26
1     1025523           2026-09-26
2     1973896           2026-09-26

## Python to SQL

### Matching tables in SQL
```sql
-- Drop the database if it already exists
DROP DATABASE IF EXISTS sql_ETL_cities;

-- Create the database
CREATE DATABASE sql_ETL_cities;

-- Use the database
USE sql_ETL_cities;

-- Create the 'cities' table
CREATE TABLE cities (
    city_id INT AUTO_INCREMENT, -- Automatically generated ID for each city
    city VARCHAR(255) NOT NULL, -- Name of the city
    latitude FLOAT, -- Latitude of the city
    longitude FLOAT, -- Longitude of the city
    country VARCHAR(255), -- Name of the city's country
    PRIMARY KEY (city_id) -- Primary key to uniquely identify each city
);

-- Create the 'populations' table
CREATE TABLE populations (
    city_id INT AUTO_INCREMENT, -- Automatically generated ID for each city
	population INT, -- number for population
    timestamp_population DATE, -- When the data was retrieved
    PRIMARY KEY (city_id), -- Primary key to uniquely identify each book
    FOREIGN KEY (city_id) REFERENCES cities(city_id) -- Foreign key to connect the population to the cities
);
```

In [26]:
# connecting to SQL
# password within .env file
load_dotenv()

schema = os.environ["schema_name"]
host = os.environ["host_address"]
user = os.environ["user_name"]
password = os.environ["password"]
port = os.environ["port_number"]

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

Connect cities_df with SQL and then load it.

In [27]:
cities_df.to_sql('cities',
                  if_exists='append',
                  con=connection_string,
                  index=False)

3

In [28]:
cities_from_sql = pd.read_sql("cities", con=connection_string)
cities_from_sql

   city_id     city  latitude  longitude   country
0        1   Berlin   52.5200   13.40500   Germany
1        2  Hamburg   53.5500   10.00000   Germany
2        3  Cologne   50.9364    6.95278   Germany

Connect population_df with SQL and then load it.

In [29]:
population_df.to_sql('populations',
                  if_exists='append',
                  con=connection_string,
                  index=False)

3

In [30]:
population_from_sql = pd.read_sql("populations", con=connection_string)
population_from_sql

   population timestamp_population
0     3596999           2026-09-26
1     1025523           2026-09-26
2     1973896           2026-09-26

## Gathering Data from OpenWeather
Using the 5 day weather forecast (5 day / 3 hour forecast data) API

In [31]:
# Example gathering data for Berlin
load_dotenv()
latitude = 52.520008
longitude = 13.404954

API_key = os.environ["openWeatherApi"]

# check out the docs for more info on making an api call https://openweathermap.org/forecast5
url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")

response = requests.get(url)
json = response.json()

json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1790445600,
   'main': {'temp': 18.77,
    'feels_like': 18.3,
    'temp_min': 16.88,
    'temp_max': 18.77,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1018,
    'humidity': 61,
    'temp_kf': 1.89,
    'dew_point': 11.1},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 92},
   'wind': {'speed': 1.37, 'deg': 336, 'gust': 2.48},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-26 18:00:00'},
  {'dt': 1790456400,
   'main': {'temp': 13.96,
    'feels_like': 13.32,
    'temp_min': 11.08,
    'temp_max': 13.96,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 73,
    'temp_kf': 2.88,
    'dew_point': 9.2},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 62},
   'wind': {'speed': 1.79, 'deg': 31, 'gust': 3.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-26 21:00:00'},
  {'dt': 1790467200,
   'main': {'temp': 11.23,
    'feels_like': 10.63,
    'temp_min': 11.23,
    'temp_max': 11.23,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 85,
    'temp_kf': 0,
    'dew_point': 9.18},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 82},
   'wind': {'speed': 2.04, 'deg': 64, 'gust': 3.78},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-27 00:00:00'},
  {'dt': 1790478000,
   'main': {'temp': 10.2,
    'feels_like': 9.6,
    'temp_min': 10.2,
    'temp_max': 10.2,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 89,
    'temp_kf': 0,
    'dew_point': 8.66},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.28, 'deg': 81, 'gust': 4.29},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-27 03:00:00'},
  {'dt': 1790488800,
   'main': {'temp': 12.67,
    'feels_like': 12.21,
    'temp_min': 12.67,
    'temp_max': 12.67,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 85,
    'temp_kf': 0,
    'dew_point': 8.4},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 66},
   'wind': {'speed': 3.04, 'deg': 97, 'gust': 5.87},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-27 06:00:00'},
  {'dt': 1790499600,
   'main': {'temp': 19.34,
    'feels_like': 19.13,
    'temp_min': 19.34,
    'temp_max': 19.34,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 69,
    'temp_kf': 0,
    'dew_point': 10.78},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 78},
   'wind': {'speed': 2.67, 'deg': 107, 'gust': 6.52},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-27 09:00:00'},
  {'dt': 1790510400,
   'main': {'temp': 21.52,
    'feels_like': 20.98,
    'temp_min': 21.52,
    'temp_max': 21.52,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 48,
    'temp_kf': 0,
    'dew_point': 9.9},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 14},
   'wind': {'speed': 3.81, 'deg': 130, 'gust': 8.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-27 12:00:00'},
  {'dt': 1790521200,
   'main': {'temp': 21.68,
    'feels_like': 21.21,
    'temp_min': 21.68,
    'temp_max': 21.68,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 50,
    'temp_kf': 0,
    'dew_point': 10.53},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.48, 'deg': 126, 'gust': 7.37},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-27 15:00:00'},
  {'dt': 1790532000,
   'main': {'temp': 18.87,
    'feels_like': 18.56,
    'temp_min': 18.87,
    'temp_max': 18.87,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 67,
    'temp_kf': 0,
    'dew_point': 10.68},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 6},
   'wind': {'speed': 3.47, 'deg': 125, 'gust': 6.78},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-27 18:00:00'},
  {'dt': 1790542800,
   'main': {'temp': 15.94,
    'feels_like': 15.57,
    'temp_min': 15.94,
    'temp_max': 15.94,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 76,
    'temp_kf': 0,
    'dew_point': 10.36},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.83, 'deg': 133, 'gust': 7.56},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-27 21:00:00'},
  {'dt': 1790553600,
   'main': {'temp': 13.63,
    'feels_like': 13.14,
    'temp_min': 13.63,
    'temp_max': 13.63,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 80,
    'temp_kf': 0,
    'dew_point': 9.96},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 43},
   'wind': {'speed': 3.68, 'deg': 138, 'gust': 7.22},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-28 00:00:00'},
  {'dt': 1790564400,
   'main': {'temp': 12.74,
    'feels_like': 12.21,
    'temp_min': 12.74,
    'temp_max': 12.74,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 82,
    'temp_kf': 0,
    'dew_point': 9.6},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 20},
   'wind': {'speed': 3.53, 'deg': 138, 'gust': 6.95},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-28 03:00:00'},
  {'dt': 1790575200,
   'main': {'temp': 14.04,
    'feels_like': 13.69,
    'temp_min': 14.04,
    'temp_max': 14.04,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1016,
    'humidity': 84,
    'temp_kf': 0,
    'dew_point': 9.46},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 52},
   'wind': {'speed': 3.21, 'deg': 143, 'gust': 6.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-28 06:00:00'},
  {'dt': 1790586000,
   'main': {'temp': 17.25,
    'feels_like': 16.81,
    'temp_min': 17.25,
    'temp_max': 17.25,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 68,
    'temp_kf': 0,
    'dew_point': 11.23},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 12},
   'wind': {'speed': 2.33, 'deg': 148, 'gust': 6.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-28 09:00:00'},
  {'dt': 1790596800,
   'main': {'temp': 21.91,
    'feels_like': 21.59,
    'temp_min': 21.91,
    'temp_max': 21.91,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 55,
    'temp_kf': 0,
    'dew_point': 12.62},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 24},
   'wind': {'speed': 2.08, 'deg': 165, 'gust': 5.75},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-28 12:00:00'},
  {'dt': 1790607600,
   'main': {'temp': 23.02,
    'feels_like': 22.74,
    'temp_min': 23.02,
    'temp_max': 23.02,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 52,
    'temp_kf': 0,
    'dew_point': 12.89},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 12},
   'wind': {'speed': 1.37, 'deg': 172, 'gust': 3.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-28 15:00:00'},
  {'dt': 1790618400,
   'main': {'temp': 18.64,
    'feels_like': 18.49,
    'temp_min': 18.64,
    'temp_max': 18.64,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1017,
    'humidity': 74,
    'temp_kf': 0,
    'dew_point': 14.03},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 37},
   'wind': {'speed': 1.9, 'deg': 120, 'gust': 3.59},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-28 18:00:00'},
  {'dt': 1790629200,
   'main': {'temp': 16.26,
    'feels_like': 16.06,
    'temp_min': 16.26,
    'temp_max': 16.26,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 81,
    'temp_kf': 0,
    'dew_point': 12.92},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 90},
   'wind': {'speed': 2.25, 'deg': 135, 'gust': 4.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-28 21:00:00'},
  {'dt': 1790640000,
   'main': {'temp': 14.38,
    'feels_like': 14.17,
    'temp_min': 14.38,
    'temp_max': 14.38,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1018,
    'humidity': 88,
    'temp_kf': 0,
    'dew_point': 12.32},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.15, 'deg': 124, 'gust': 4.05},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-29 00:00:00'},
  {'dt': 1790650800,
   'main': {'temp': 13.21,
    'feels_like': 12.91,
    'temp_min': 13.21,
    'temp_max': 13.21,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 89,
    'temp_kf': 0,
    'dew_point': 11.44},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 76},
   'wind': {'speed': 2.24, 'deg': 121, 'gust': 4.24},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-29 03:00:00'},
  {'dt': 1790661600,
   'main': {'temp': 13.07,
    'feels_like': 12.63,
    'temp_min': 13.07,
    'temp_max': 13.07,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 84,
    'temp_kf': 0,
    'dew_point': 10.48},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 44},
   'wind': {'speed': 2.82, 'deg': 125, 'gust': 5.52},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-29 06:00:00'},
  {'dt': 1790672400,
   'main': {'temp': 18.29,
    'feels_like': 17.82,
    'temp_min': 18.29,
    'temp_max': 18.29,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 63,
    'temp_kf': 0,
    'dew_point': 11.29},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 17},
   'wind': {'speed': 2.84, 'deg': 133, 'gust': 7.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-29 09:00:00'},
  {'dt': 1790683200,
   'main': {'temp': 22.61,
    'feels_like': 22.18,
    'temp_min': 22.61,
    'temp_max': 22.61,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 48,
    'temp_kf': 0,
    'dew_point': 11.2},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 3.18, 'deg': 133, 'gust': 7.86},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-29 12:00:00'},
  {'dt': 1790694000,
   'main': {'temp': 22.68,
    'feels_like': 22.18,
    'temp_min': 22.68,
    'temp_max': 22.68,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 45,
    'temp_kf': 0,
    'dew_point': 10.34},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 10},
   'wind': {'speed': 3.57, 'deg': 121, 'gust': 7.59},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-29 15:00:00'},
  {'dt': 1790704800,
   'main': {'temp': 17.82,
    'feels_like': 17.28,
    'temp_min': 17.82,
    'temp_max': 17.82,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 62,
    'temp_kf': 0,
    'dew_point': 10.55},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.12, 'deg': 121, 'gust': 6.04},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-29 18:00:00'},
  {'dt': 1790715600,
   'main': {'temp': 15.55,
    'feels_like': 15.12,
    'temp_min': 15.55,
    'temp_max': 15.55,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 75,
    'temp_kf': 0,
    'dew_point': 11.18},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 3.36, 'deg': 123, 'gust': 6.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-29 21:00:00'},
  {'dt': 1790726400,
   'main': {'temp': 14.52,
    'feels_like': 13.86,
    'temp_min': 14.52,
    'temp_max': 14.52,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 70,
    'temp_kf': 0,
    'dew_point': 9.08},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 8},
   'wind': {'speed': 3.61, 'deg': 133, 'gust': 7.06},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-30 00:00:00'},
  {'dt': 1790737200,
   'main': {'temp': 12.93,
    'feels_like': 12.18,
    'temp_min': 12.93,
    'temp_max': 12.93,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 73,
    'temp_kf': 0,
    'dew_point': 8.21},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.92, 'deg': 121, 'gust': 7.79},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-30 03:00:00'},
  {'dt': 1790748000,
   'main': {'temp': 12.91,
    'feels_like': 12.08,
    'temp_min': 12.91,
    'temp_max': 12.91,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 70,
    'temp_kf': 0,
    'dew_point': 7.64},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 36},
   'wind': {'speed': 4.08, 'deg': 124, 'gust': 8.24},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-30 06:00:00'},
  {'dt': 1790758800,
   'main': {'temp': 17.56,
    'feels_like': 16.81,
    'temp_min': 17.56,
    'temp_max': 17.56,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1018,
    'humidity': 55,
    'temp_kf': 0,
    'dew_point': 8.42},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 4.47, 'deg': 125, 'gust': 10.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-30 09:00:00'},
  {'dt': 1790769600,
   'main': {'temp': 21.05,
    'feels_like': 20.39,
    'temp_min': 21.05,
    'temp_max': 21.05,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 45,
    'temp_kf': 0,
    'dew_point': 8.9},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.08, 'deg': 140, 'gust': 9.66},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-30 12:00:00'},
  {'dt': 1790780400,
   'main': {'temp': 21.28,
    'feels_like': 20.69,
    'temp_min': 21.28,
    'temp_max': 21.28,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 47,
    'temp_kf': 0,
    'dew_point': 9.75},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 95},
   'wind': {'speed': 3.65, 'deg': 133, 'gust': 7.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-09-30 15:00:00'},
  {'dt': 1790791200,
   'main': {'temp': 17.68,
    'feels_like': 17.15,
    'temp_min': 17.68,
    'temp_max': 17.68,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1017,
    'humidity': 63,
    'temp_kf': 0,
    'dew_point': 10.55},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 99},
   'wind': {'speed': 3.14, 'deg': 128, 'gust': 6.09},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-30 18:00:00'},
  {'dt': 1790802000,
   'main': {'temp': 15.31,
    'feels_like': 14.83,
    'temp_min': 15.31,
    'temp_max': 15.31,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 74,
    'temp_kf': 0,
    'dew_point': 10.66},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.84, 'deg': 129, 'gust': 5.49},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-09-30 21:00:00'},
  {'dt': 1790812800,
   'main': {'temp': 14.34,
    'feels_like': 13.87,
    'temp_min': 14.34,
    'temp_max': 14.34,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 78,
    'temp_kf': 0,
    'dew_point': 10.52},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.47, 'deg': 132, 'gust': 4.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-10-01 00:00:00'},
  {'dt': 1790823600,
   'main': {'temp': 13.41,
    'feels_like': 12.92,
    'temp_min': 13.41,
    'temp_max': 13.41,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 81,
    'temp_kf': 0,
    'dew_point': 10.28},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 2.35, 'deg': 136, 'gust': 4.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-10-01 03:00:00'},
  {'dt': 1790834400,
   'main': {'temp': 12.96,
    'feels_like': 12.48,
    'temp_min': 12.96,
    'temp_max': 12.96,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 83,
    'temp_kf': 0,
    'dew_point': 10.1},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.97, 'deg': 144, 'gust': 3.79},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-10-01 06:00:00'},
  {'dt': 1790845200,
   'main': {'temp': 16.94,
    'feels_like': 16.49,
    'temp_min': 16.94,

In [32]:
# output is a dictionary
json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [33]:
json['cod']

'200'

In [34]:
json['message']

0

In [35]:
json['cnt']

40

In [36]:
json['list']

[{'dt': 1790445600,
  'main': {'temp': 18.77,
   'feels_like': 18.3,
   'temp_min': 16.88,
   'temp_max': 18.77,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1018,
   'humidity': 61,
   'temp_kf': 1.89,
   'dew_point': 11.1},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 92},
  'wind': {'speed': 1.37, 'deg': 336, 'gust': 2.48},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-26 18:00:00'},
 {'dt': 1790456400,
  'main': {'temp': 13.96,
   'feels_like': 13.32,
   'temp_min': 11.08,
   'temp_max': 13.96,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1019,
   'humidity': 73,
   'temp_kf': 2.88,
   'dew_point': 9.2},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 62},
  'wind': {'speed': 1.79, 'deg': 31, 'gust': 3.31},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-26 21:00:00'},
 {'dt': 1790467200,
  'main': {'temp': 11.23,
   'feels_like': 10.63,
   'temp_min': 11.23,
   'temp_max': 11.23,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 85,
   'temp_kf': 0,
   'dew_point': 9.18},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 82},
  'wind': {'speed': 2.04, 'deg': 64, 'gust': 3.78},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-27 00:00:00'},
 {'dt': 1790478000,
  'main': {'temp': 10.2,
   'feels_like': 9.6,
   'temp_min': 10.2,
   'temp_max': 10.2,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 89,
   'temp_kf': 0,
   'dew_point': 8.66},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 2.28, 'deg': 81, 'gust': 4.29},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-27 03:00:00'},
 {'dt': 1790488800,
  'main': {'temp': 12.67,
   'feels_like': 12.21,
   'temp_min': 12.67,
   'temp_max': 12.67,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 85,
   'temp_kf': 0,
   'dew_point': 8.4},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 66},
  'wind': {'speed': 3.04, 'deg': 97, 'gust': 5.87},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-27 06:00:00'},
 {'dt': 1790499600,
  'main': {'temp': 19.34,
   'feels_like': 19.13,
   'temp_min': 19.34,
   'temp_max': 19.34,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 69,
   'temp_kf': 0,
   'dew_point': 10.78},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 78},
  'wind': {'speed': 2.67, 'deg': 107, 'gust': 6.52},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-27 09:00:00'},
 {'dt': 1790510400,
  'main': {'temp': 21.52,
   'feels_like': 20.98,
   'temp_min': 21.52,
   'temp_max': 21.52,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 48,
   'temp_kf': 0,
   'dew_point': 9.9},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 14},
  'wind': {'speed': 3.81, 'deg': 130, 'gust': 8.96},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-27 12:00:00'},
 {'dt': 1790521200,
  'main': {'temp': 21.68,
   'feels_like': 21.21,
   'temp_min': 21.68,
   'temp_max': 21.68,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 50,
   'temp_kf': 0,
   'dew_point': 10.53},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.48, 'deg': 126, 'gust': 7.37},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-27 15:00:00'},
 {'dt': 1790532000,
  'main': {'temp': 18.87,
   'feels_like': 18.56,
   'temp_min': 18.87,
   'temp_max': 18.87,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 67,
   'temp_kf': 0,
   'dew_point': 10.68},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 6},
  'wind': {'speed': 3.47, 'deg': 125, 'gust': 6.78},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-27 18:00:00'},
 {'dt': 1790542800,
  'main': {'temp': 15.94,
   'feels_like': 15.57,
   'temp_min': 15.94,
   'temp_max': 15.94,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 76,
   'temp_kf': 0,
   'dew_point': 10.36},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.83, 'deg': 133, 'gust': 7.56},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-27 21:00:00'},
 {'dt': 1790553600,
  'main': {'temp': 13.63,
   'feels_like': 13.14,
   'temp_min': 13.63,
   'temp_max': 13.63,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 80,
   'temp_kf': 0,
   'dew_point': 9.96},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 43},
  'wind': {'speed': 3.68, 'deg': 138, 'gust': 7.22},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-28 00:00:00'},
 {'dt': 1790564400,
  'main': {'temp': 12.74,
   'feels_like': 12.21,
   'temp_min': 12.74,
   'temp_max': 12.74,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 82,
   'temp_kf': 0,
   'dew_point': 9.6},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 20},
  'wind': {'speed': 3.53, 'deg': 138, 'gust': 6.95},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-28 03:00:00'},
 {'dt': 1790575200,
  'main': {'temp': 14.04,
   'feels_like': 13.69,
   'temp_min': 14.04,
   'temp_max': 14.04,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1016,
   'humidity': 84,
   'temp_kf': 0,
   'dew_point': 9.46},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 52},
  'wind': {'speed': 3.21, 'deg': 143, 'gust': 6.41},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-28 06:00:00'},
 {'dt': 1790586000,
  'main': {'temp': 17.25,
   'feels_like': 16.81,
   'temp_min': 17.25,
   'temp_max': 17.25,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 68,
   'temp_kf': 0,
   'dew_point': 11.23},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 12},
  'wind': {'speed': 2.33, 'deg': 148, 'gust': 6.16},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-28 09:00:00'},
 {'dt': 1790596800,
  'main': {'temp': 21.91,
   'feels_like': 21.59,
   'temp_min': 21.91,
   'temp_max': 21.91,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 55,
   'temp_kf': 0,
   'dew_point': 12.62},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 24},
  'wind': {'speed': 2.08, 'deg': 165, 'gust': 5.75},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-28 12:00:00'},
 {'dt': 1790607600,
  'main': {'temp': 23.02,
   'feels_like': 22.74,
   'temp_min': 23.02,
   'temp_max': 23.02,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 52,
   'temp_kf': 0,
   'dew_point': 12.89},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 12},
  'wind': {'speed': 1.37, 'deg': 172, 'gust': 3.16},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-28 15:00:00'},
 {'dt': 1790618400,
  'main': {'temp': 18.64,
   'feels_like': 18.49,
   'temp_min': 18.64,
   'temp_max': 18.64,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1017,
   'humidity': 74,
   'temp_kf': 0,
   'dew_point': 14.03},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 37},
  'wind': {'speed': 1.9, 'deg': 120, 'gust': 3.59},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-28 18:00:00'},
 {'dt': 1790629200,
  'main': {'temp': 16.26,
   'feels_like': 16.06,
   'temp_min': 16.26,
   'temp_max': 16.26,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 81,
   'temp_kf': 0,
   'dew_point': 12.92},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 90},
  'wind': {'speed': 2.25, 'deg': 135, 'gust': 4.26},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-28 21:00:00'},
 {'dt': 1790640000,
  'main': {'temp': 14.38,
   'feels_like': 14.17,
   'temp_min': 14.38,
   'temp_max': 14.38,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1018,
   'humidity': 88,
   'temp_kf': 0,
   'dew_point': 12.32},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 97},
  'wind': {'speed': 2.15, 'deg': 124, 'gust': 4.05},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-29 00:00:00'},
 {'dt': 1790650800,
  'main': {'temp': 13.21,
   'feels_like': 12.91,
   'temp_min': 13.21,
   'temp_max': 13.21,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 89,
   'temp_kf': 0,
   'dew_point': 11.44},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 76},
  'wind': {'speed': 2.24, 'deg': 121, 'gust': 4.24},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-29 03:00:00'},
 {'dt': 1790661600,
  'main': {'temp': 13.07,
   'feels_like': 12.63,
   'temp_min': 13.07,
   'temp_max': 13.07,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 84,
   'temp_kf': 0,
   'dew_point': 10.48},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 44},
  'wind': {'speed': 2.82, 'deg': 125, 'gust': 5.52},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-29 06:00:00'},
 {'dt': 1790672400,
  'main': {'temp': 18.29,
   'feels_like': 17.82,
   'temp_min': 18.29,
   'temp_max': 18.29,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 63,
   'temp_kf': 0,
   'dew_point': 11.29},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 17},
  'wind': {'speed': 2.84, 'deg': 133, 'gust': 7.16},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-29 09:00:00'},
 {'dt': 1790683200,
  'main': {'temp': 22.61,
   'feels_like': 22.18,
   'temp_min': 22.61,
   'temp_max': 22.61,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 48,
   'temp_kf': 0,
   'dew_point': 11.2},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 2},
  'wind': {'speed': 3.18, 'deg': 133, 'gust': 7.86},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-29 12:00:00'},
 {'dt': 1790694000,
  'main': {'temp': 22.68,
   'feels_like': 22.18,
   'temp_min': 22.68,
   'temp_max': 22.68,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 45,
   'temp_kf': 0,
   'dew_point': 10.34},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 10},
  'wind': {'speed': 3.57, 'deg': 121, 'gust': 7.59},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-29 15:00:00'},
 {'dt': 1790704800,
  'main': {'temp': 17.82,
   'feels_like': 17.28,
   'temp_min': 17.82,
   'temp_max': 17.82,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 62,
   'temp_kf': 0,
   'dew_point': 10.55},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.12, 'deg': 121, 'gust': 6.04},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-29 18:00:00'},
 {'dt': 1790715600,
  'main': {'temp': 15.55,
   'feels_like': 15.12,
   'temp_min': 15.55,
   'temp_max': 15.55,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 75,
   'temp_kf': 0,
   'dew_point': 11.18},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 5},
  'wind': {'speed': 3.36, 'deg': 123, 'gust': 6.53},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-29 21:00:00'},
 {'dt': 1790726400,
  'main': {'temp': 14.52,
   'feels_like': 13.86,
   'temp_min': 14.52,
   'temp_max': 14.52,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 70,
   'temp_kf': 0,
   'dew_point': 9.08},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 8},
  'wind': {'speed': 3.61, 'deg': 133, 'gust': 7.06},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-30 00:00:00'},
 {'dt': 1790737200,
  'main': {'temp': 12.93,
   'feels_like': 12.18,
   'temp_min': 12.93,
   'temp_max': 12.93,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 73,
   'temp_kf': 0,
   'dew_point': 8.21},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.92, 'deg': 121, 'gust': 7.79},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-30 03:00:00'},
 {'dt': 1790748000,
  'main': {'temp': 12.91,
   'feels_like': 12.08,
   'temp_min': 12.91,
   'temp_max': 12.91,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 70,
   'temp_kf': 0,
   'dew_point': 7.64},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 36},
  'wind': {'speed': 4.08, 'deg': 124, 'gust': 8.24},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-30 06:00:00'},
 {'dt': 1790758800,
  'main': {'temp': 17.56,
   'feels_like': 16.81,
   'temp_min': 17.56,
   'temp_max': 17.56,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1018,
   'humidity': 55,
   'temp_kf': 0,
   'dew_point': 8.42},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 86},
  'wind': {'speed': 4.47, 'deg': 125, 'gust': 10.31},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-30 09:00:00'},
 {'dt': 1790769600,
  'main': {'temp': 21.05,
   'feels_like': 20.39,
   'temp_min': 21.05,
   'temp_max': 21.05,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 45,
   'temp_kf': 0,
   'dew_point': 8.9},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.08, 'deg': 140, 'gust': 9.66},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-30 12:00:00'},
 {'dt': 1790780400,
  'main': {'temp': 21.28,
   'feels_like': 20.69,
   'temp_min': 21.28,
   'temp_max': 21.28,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1017,
   'humidity': 47,
   'temp_kf': 0,
   'dew_point': 9.75},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 95},
  'wind': {'speed': 3.65, 'deg': 133, 'gust': 7.74},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-09-30 15:00:00'},
 {'dt': 1790791200,
  'main': {'temp': 17.68,
   'feels_like': 17.15,
   'temp_min': 17.68,
   'temp_max': 17.68,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1017,
   'humidity': 63,
   'temp_kf': 0,
   'dew_point': 10.55},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 99},
  'wind': {'speed': 3.14, 'deg': 128, 'gust': 6.09},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-30 18:00:00'},
 {'dt': 1790802000,
  'main': {'temp': 15.31,
   'feels_like': 14.83,
   'temp_min': 15.31,
   'temp_max': 15.31,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 74,
   'temp_kf': 0,
   'dew_point': 10.66},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.84, 'deg': 129, 'gust': 5.49},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-09-30 21:00:00'},
 {'dt': 1790812800,
  'main': {'temp': 14.34,
   'feels_like': 13.87,
   'temp_min': 14.34,
   'temp_max': 14.34,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 78,
   'temp_kf': 0,
   'dew_point': 10.52},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.47, 'deg': 132, 'gust': 4.8},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-01 00:00:00'},
 {'dt': 1790823600,
  'main': {'temp': 13.41,
   'feels_like': 12.92,
   'temp_min': 13.41,
   'temp_max': 13.41,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1018,
   'humidity': 81,
   'temp_kf': 0,
   'dew_point': 10.28},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 96},
  'wind': {'speed': 2.35, 'deg': 136, 'gust': 4.53},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-10-01 03:00:00'},
 {'dt': 1790834400,
  'main': {'temp': 12.96,
   'feels_like': 12.48,
   'temp_min': 12.96,
   'temp_max': 12.96,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 83,
   'temp_kf': 0,
   'dew_point': 10.1},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.97, 'deg': 144, 'gust': 3.79},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-01 06:00:00'},
 {'dt': 1790845200,
  'main': {'temp': 16.94,
   'feels_like': 16.49,
   'temp_min': 16.94,
   'temp_max': 16.94,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 69,
   'temp_kf': 0,
   'dew_point': 11.19},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.38, 'deg': 146, 'gust': 4.18},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-10-01 09:00:00'},
 {'dt': 1790856000,
  'main': {'temp': 18.59,
   'feels_like': 18.28,
   'temp_min': 18.59,
   'temp_max': 18.59,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1021,
   'humidity': 68,
   'temp_kf': 0,
   'dew_point': 12.59},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},

In [37]:
json['list'][0]

{'dt': 1790445600,
 'main': {'temp': 18.77,
  'feels_like': 18.3,
  'temp_min': 16.88,
  'temp_max': 18.77,
  'pressure': 1022,
  'sea_level': 1022,
  'grnd_level': 1018,
  'humidity': 61,
  'temp_kf': 1.89,
  'dew_point': 11.1},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04n'}],
 'clouds': {'all': 92},
 'wind': {'speed': 1.37, 'deg': 336, 'gust': 2.48},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'n'},
 'dt_txt': '2026-09-26 18:00:00'}

In [38]:
json['city']

{'id': 6545310,
 'name': 'Mitte',
 'coord': {'lat': 52.52, 'lon': 13.405},
 'country': 'DE',
 'population': 329078,
 'timezone': 7200,
 'sunrise': 1790398713,
 'sunset': 1790441820}

Gathering the important information from the data

In [39]:
json['list'][0]['dt_txt']

'2026-09-26 18:00:00'

In [40]:
json['list'][0]['main']['temp']

18.77

In [41]:
json['list'][0]['main']['feels_like']

18.3

In [42]:
json['list'][0]['weather'][0]['description']

'overcast clouds'

In [43]:
json['list'][0]['wind']['speed']

1.37

In [44]:
# check if it has rained in the last 3 hours if not enter 0
json['list'][0].get('rain', {}).get('3h', 0)

0

Creating a DataFrame

In [45]:
berlin_weathers= []

for item in json['list']:
    berlin_weather = {
        'forecast_time': item.get('dt_txt', None),
        'temperature': item['main'].get('temp', None),
        'feels_like': item['main'].get('feels_like', None),
        'forecast': item['weather'][0].get('description', None),
         'rain': item.get('rain', {}).get('3h', 0),
        'wind': item['wind'].get('speed', None)   
     }
    
    berlin_weathers.append(berlin_weather)

berlin_weather_df = pd.DataFrame(berlin_weathers)
berlin_weather_df

          forecast_time  temperature  feels_like          forecast  rain  wind
0   2026-09-26 18:00:00        18.77       18.30   overcast clouds     0  1.37
1   2026-09-26 21:00:00        13.96       13.32     broken clouds     0  1.79
2   2026-09-27 00:00:00        11.23       10.63     broken clouds     0  2.04
3   2026-09-27 03:00:00        10.20        9.60         clear sky     0  2.28
4   2026-09-27 06:00:00        12.67       12.21     broken clouds     0  3.04
5   2026-09-27 09:00:00        19.34       19.13     broken clouds     0  2.67
6   2026-09-27 12:00:00        21.52       20.98        few clouds     0  3.81
7   2026-09-27 15:00:00        21.68       21.21         clear sky     0  3.48
8   2026-09-27 18:00:00        18.87       18.56         clear sky     0  3.47
9   2026-09-27 21:00:00        15.94       15.57         clear sky     0  3.83
10  2026-09-28 00:00:00        13.63       13.14  scattered clouds     0  3.68
11  2026-09-28 03:00:00        12.74       12.21        few clouds     0  3.53
12  2026-09-28 06:00:00        14.04       13.69     broken clouds     0  3.21
13  2026-09-28 09:00:00        17.25       16.81        few clouds     0  2.33
14  2026-09-28 12:00:00        21.91       21.59        few clouds     0  2.08
15  2026-09-28 15:00:00        23.02       22.74        few clouds     0  1.37
16  2026-09-28 18:00:00        18.64       18.49  scattered clouds     0  1.90
17  2026-09-28 21:00:00        16.26       16.06   overcast clouds     0  2.25
18  2026-09-29 00:00:00        14.38       14.17   overcast clouds     0  2.15
19  2026-09-29 03:00:00        13.21       12.91     broken clouds     0  2.24
20  2026-09-29 06:00:00        13.07       12.63  scattered clouds     0  2.82
21  2026-09-29 09:00:00        18.29       17.82        few clouds     0  2.84
22  2026-09-29 12:00:00        22.61       22.18         clear sky     0  3.18
23  2026-09-29 15:00:00        22.68       22.18         clear sky     0  3.57
24  2026-09-29 18:00:00        17.82       17.28         clear sky     0  3.12
25  2026-09-29 21:00:00        15.55       15.12         clear sky     0  3.36
26  2026-09-30 00:00:00        14.52       13.86         clear sky     0  3.61
27  2026-09-30 03:00:00        12.93       12.18         clear sky     0  3.92
28  2026-09-30 06:00:00        12.91       12.08  scattered clouds     0  4.08
29  2026-09-30 09:00:00        17.56       16.81   overcast clouds     0  4.47
30  2026-09-30 12:00:00        21.05       20.39   overcast clouds     0  4.08
31  2026-09-30 15:00:00        21.28       20.69   overcast clouds     0  3.65
32  2026-09-30 18:00:00        17.68       17.15   overcast clouds     0  3.14
33  2026-09-30 21:00:00        15.31       14.83   overcast clouds     0  2.84
34  2026-10-01 00:00:00        14.34       13.87   overcast clouds     0  2.47
35  2026-10-01 03:00:00        13.41       12.92   overcast clouds     0  2.35
36  2026-10-01 06:00:00        12.96       12.48   overcast clouds     0  1.97
37  2026-10-01 09:00:00        16.94       16.49   overcast clouds     0  1.38
38  2026-10-01 12:00:00        18.59       18.28   overcast clouds     0  0.60
39  2026-10-01 15:00:00        20.52       20.30     broken clouds     0  0.56

## Gathering weather data from SQL as well as putting it into a 'weathers' table for the cities

In [46]:
# Create a function to get the data from all three cities

def gather_weather_datas(cities):

   # Get the data and information from SQL

   schema = os.environ["schema_name"]
   host = os.environ["host_address"]
   user = os.environ["user_name"]
   password = os.environ["password"]
   port = os.environ["port_number"]

   connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

   # get the data from the 'cities' table
   cities_from_sql = pd.read_sql("cities", con=connection_string)
   cities_from_sql


   API_key = os.environ["openWeatherApi"]
   weathers= []


   for _, city in cities_from_sql.iterrows(): # iterrows returns index and a value, i dont need the index

      latitude = city["latitude"]
      longitude = city["longitude"]
      city_id = city["city_id"]

      url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")
      response = requests.get(url)
      weather_data = response.json()

      # Creating a DataFrame from the data
      for item in weather_data['list']:
         weather = {
            "city_id": city_id,
            'forecast_time': item.get('dt_txt', None),
            'temperature': item['main'].get('temp', None),
            'feels_like': item['main'].get('feels_like', None),
            'forecast': item['weather'][0].get('description', None),
            'rain': item.get('rain', {}).get('3h', 0),
            'wind': item['wind'].get('speed', None)   
         } 
         weathers.append(weather)

   weather_df = pd.DataFrame(weathers)
   return weather_df

In [47]:
cities_weather_df = gather_weather_datas(["Berlin", "Hamburg", "Munich"])
cities_weather_df

,city_id,forecast_time,temperature,feels_like,forecast,rain,wind
0,1,2026-09-26 18:00:00,18.77,18.30,overcast clouds,0.00,1.37
1,1,2026-09-26 21:00:00,13.96,13.32,broken clouds,0.00,1.79
2,1,2026-09-27 00:00:00,11.23,10.63,broken clouds,0.00,2.04
3,1,2026-09-27 03:00:00,10.20,9.60,clear sky,0.00,2.28
4,1,2026-09-27 06:00:00,12.67,12.21,broken clouds,0.00,3.04
...,...,...,...,...,...,...,...
115,3,2026-10-01 03:00:00,17.99,18.40,light rain,2.55,1.00
116,3,2026-10-01 06:00:00,17.17,17.45,light rain,1.53,2.11
117,3,2026-10-01 09:00:00,19.18,19.29,overcast clouds,0.00,0.88
118,3,2026-10-01 12:00:00,21.25,21.18,overcast clouds,0.00,0.75
119,3,2026-10-01 15:00:00,21.70,21.54,overcast clouds,0.00,0.83

weather_df to 'weathers' table in SQL

In [48]:
cities_weather_df.to_sql('weathers',
                  if_exists='append',
                  con=connection_string,
                  index=False)

120

## Flight data using the AeroDataBoxAPI

### Airport API by location

Goal: to extract information on flights to our cities

- what does the API ned to work?
  - airport API needs lat, lon
  - flights API needs ICAO codes to work
- make the API call
  - first API call: I can make a first API call to get the airport codes
  - second API call: I can use the codes then to make the flights API call
- exploring and extracting the info I need from response json
- it will al lbe put into a DataFrame
- The DF gets send to the database in MySQL

Start with Airport API to get the airports based on location: \
First attempt with Berlin

In [49]:
load_dotenv()

headers = {
	"x-rapidapi-key": os.environ["x-rapidapi-key"],
	"x-rapidapi-host": os.environ["x-rapidapi-host"],
    "Content-Type": os.environ["Content-Type"]
}

url = "https://aerodatabox.p.rapidapi.com/airports/search/location"

querystring = {"withFlightInfoOnly":"True","radiusKm":"50","limit":"10","lat":"52.31","lon":"13.24"}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'searchBy': {'lat': 52.31, 'lon': 13.24}, 'count': 2, 'items': [{'icao': 'EDDB', 'iata': 'BER', 'name': 'Berlin Brandenburg', 'shortName': 'Brandenburg', 'municipalityName': 'Berlin', 'location': {'lat': 52.35139, 'lon': 13.493889}, 'countryCode': 'DE', 'timeZone': 'Europe/Berlin'}, {'icao': 'EDDT', 'iata': 'TXL', 'name': 'Berlin -Tegel', 'shortName': '-Tegel', 'municipalityName': 'Berlin', 'location': {'lat': 52.5597, 'lon': 13.287699}, 'countryCode': 'DE', 'timeZone': 'Europe/Berlin'}]}

Turning the API's data into a DataFrame with `.json_normalize()`

In [50]:
pd.json_normalize(response.json()['items'])

,icao,iata,name,shortName,municipalityName,countryCode,timeZone,location.lat,location.lon
0,EDDB,BER,Berlin Brandenburg,Brandenburg,Berlin,DE,Europe/Berlin,52.35139,13.493889
1,EDDT,TXL,Berlin -Tegel,-Tegel,Berlin,DE,Europe/Berlin,52.55970,13.287699

Gathering the data for multiple cities, using their latitude and longitude

In [51]:
def get_airports(latitudes, longitudes):
    # API headers
    headers = {
	"x-rapidapi-key": os.environ["x-rapidapi-key"],
	"x-rapidapi-host": os.environ["x-rapidapi-host"],
    "Content-Type": os.environ["Content-Type"]
    }

    # DataFrame to store results
    all_airports = []

    for lat, lon in zip(latitudes, longitudes):
    # Construct the URL with the latitude and longitude
        url = url = "https://aerodatabox.p.rapidapi.com/airports/search/location"
        querystring = {"lat":lat,"lon":lon,"radiusKm":"50","limit":"10","withFlightInfoOnly":"true"}

        # Make the API request
        response = requests.get(url, headers=headers, params=querystring)

        if response.status_code == 200:
            data = response.json()
            airports = pd.json_normalize(data.get('items', []))
            all_airports.append(airports)

    return pd.concat(all_airports, ignore_index=True)

Using the latitudes and longitudes from the citites table

In [52]:
# coordinates for Berlin, Hamburg, Munich
latitudes = [52.5200, 53.55, 50.9364]
longitudes = [13.4050, 10, 6.95278]

airports_table  = get_airports(latitudes, longitudes)
airports_table

,icao,iata,name,shortName,municipalityName,countryCode,timeZone,location.lat,location.lon
0,EDDT,TXL,Berlin -Tegel,-Tegel,Berlin,DE,Europe/Berlin,52.55970,13.287699
1,EDDB,BER,Berlin Brandenburg,Brandenburg,Berlin,DE,Europe/Berlin,52.35139,13.493889
2,EDDH,HAM,Hamburg,Hamburg,Hamburg,DE,Europe/Berlin,53.63040,9.988229
3,EDDK,CGN,Cologne Bonn,Bonn,Cologne,DE,Europe/Berlin,50.86590,7.142739
4,EDDL,DUS,Düsseldorf,Düsseldorf,Düsseldorf,DE,Europe/Berlin,51.28950,6.766779

#### Create the DataFrames for SQL

First add more tables to SQL:
```sql
-- Create 'weathers' table
CREATE TABLE weathers(
	weather_entry_id INT AUTO_INCREMENT NOT NULL, -- Automatically generated for each weather entry
    city_id INT NOT NULL, -- ID for each city
    forecast_time DATETIME, -- Date and time of the forecast
    temperature FLOAT, -- temperature of the forecast
    feels_like FLOAT, -- what the temperature feels like
    forecast VARCHAR(255), -- weather forecast
    rain FLOAT, -- whether it has rained or not and how much in mm
    wind FLOAT, -- wind speed
    PRIMARY KEY (weather_entry_id),
    FOREIGN KEY (city_id) REFERENCES cities(city_id) -- foreign key to connect weather data to cities
);

-- Create 'airports' table
CREATE TABLE airports (
	airport_icao VARCHAR(25), -- icao of the airport
    airport_name VARCHAR(255), -- the name of the airport
    PRIMARY KEY (airport_icao)
);

-- Create 'cities_airports' table
CREATE TABLE cities_airports(
	city_id INT, -- ID of the city
    airport_icao VARCHAR(5), -- icao of the city's airport
	FOREIGN KEY (city_id) REFERENCES cities(city_id), -- forgein key to connect cities_airports to cities
    FOREIGN KEY (airport_icao) REFERENCES airports(airport_icao) -- foreign key to connect cities_airports to airports
);

-- Create 'flights' table
CREATE TABLE flights (
	flight_id INT AUTO_INCREMENT NOT NULL, -- Automatically generated ID for each flight
    flight_number VARCHAR(25), -- the flight number, made of letters and numbers
    departure_airport_icao VARCHAR(25), -- icao of the airport the flight departed from
    arrival_airport_icao VARCHAR(25), -- icao of the airport the flight is arriving at
    scheduled_arrival_time DATETIME, -- the time when the flight arrives
    PRIMARY KEY (flight_id),
    FOREIGN KEY (arrival_airport_icao) REFERENCES airports(airport_icao) -- forgein key to connect flights to airports
);
```

In [53]:
# creating DataFrame 'airports'
airport_name = airports_table['name']
airport_icao = airports_table['icao']

airports = pd.DataFrame({'airport_icao': airport_icao,
                         'airport_name': airport_name})
airports

  airport_icao        airport_name
0         EDDT       Berlin -Tegel
1         EDDB  Berlin Brandenburg
2         EDDH             Hamburg
3         EDDK        Cologne Bonn
4         EDDL          Düsseldorf

In [54]:
# connecting the DataFrame with SQL
airports.to_sql('airports',
                if_exists='append',
                con=connection_string,
                index=False)

5

In [55]:
airports_from_sql = pd.read_sql("airports", con=connection_string)
airports_from_sql

  airport_icao        airport_name
0         EDDB  Berlin Brandenburg
1         EDDH             Hamburg
2         EDDK        Cologne Bonn
3         EDDL          Düsseldorf
4         EDDT       Berlin -Tegel

In [56]:
cities_from_sql

   city_id     city  latitude  longitude   country
0        1   Berlin   52.5200   13.40500   Germany
1        2  Hamburg   53.5500   10.00000   Germany
2        3  Cologne   50.9364    6.95278   Germany

In [57]:
# creating DataFrame 'cities_airports'
cities_airports = airports_table[['municipalityName', 'icao']].merge(
                                                                cities_from_sql[['city_id', 'city']],
                                                                left_on='municipalityName',
                                                                right_on='city',
                                                                how='left'
                                                                )
cities_airports

  municipalityName  icao  city_id     city
0           Berlin  EDDT      1.0   Berlin
1           Berlin  EDDB      1.0   Berlin
2          Hamburg  EDDH      2.0  Hamburg
3          Cologne  EDDK      3.0  Cologne
4       Düsseldorf  EDDL      NaN      NaN

In [58]:
cities_airports = cities_airports[['city_id', 'icao']]

cities_airports = cities_airports.rename(
    columns={'icao': 'airport_icao'}
)

In [59]:
cities_airports['city_id'] = cities_airports['city_id'].astype('Int64')
cities_airports

   city_id airport_icao
0        1         EDDT
1        1         EDDB
2        2         EDDH
3        3         EDDK
4     <NA>         EDDL

Düsseldorf remains without an ID since it was not one of the three cities, but one within reach of Cologne. To keep it simple I'll drop it.

In [60]:
cities_airports = cities_airports.dropna(subset=['city_id'])
cities_airports

   city_id airport_icao
0        1         EDDT
1        1         EDDB
2        2         EDDH
3        3         EDDK

In [61]:
# connecting the DataFrame with SQL
cities_airports.to_sql('cities_airports',
                        if_exists='append',
                        con=connection_string,
                        index=False)

4

In [62]:
cities_airports_from_sql = pd.read_sql("cities_airports", con=connection_string)
cities_airports_from_sql

   city_id airport_icao
0        1         EDDT
1        1         EDDB
2        2         EDDH
3        3         EDDK

### Flight API for specific date (The next day)

In [63]:
# getting tomorrow's date

today_date = datetime.now()
tomorrow  = today_date + timedelta(days=1)

tomorrow_date = tomorrow.strftime('%Y-%m-%d')
tomorrow_date

'2026-09-27'

In [64]:
# first try using icao of Berlin Brandenburg

api_key = os.environ["x-rapidapi-key"]
icao = "EDDB"
time_1 = "00:00"
time_2 = "11:59" # remaining 12 hours of the day are missing. Hours should be more than beginning of the search range, but not more than by 12 hours per API call.

url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/{icao}/{tomorrow_date}T{time_1}/{tomorrow_date}T{time_2}"

querystring = {"withLeg":"true", "direction":"Arrival", "withCancelled":"false", "withCodeshared":"true", "withCargo":"false", "withPrivate":"false"}

headers = {
	"x-rapidapi-key": os.environ["x-rapidapi-key"],
	"x-rapidapi-host": os.environ["x-rapidapi-host"],
	"Content-Type": os.environ["Content-Type"]
}
response = requests.request("GET",
                            url,
                            headers = headers,
                            params = querystring)

flights_json = response.json()

flights_json

{'arrivals': [{'departure': {'airport': {'icao': 'LTBJ',
     'iata': 'ADB',
     'name': 'İzmir',
     'countryCode': 'tr',
     'timeZone': 'Europe/Istanbul'},
    'scheduledTime': {'utc': '2026-09-27 01:00Z',
     'local': '2026-09-27 04:00+03:00'},
    'revisedTime': {'utc': '2026-09-27 01:00Z',
     'local': '2026-09-27 04:00+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 04:05Z',
     'local': '2026-09-27 06:05+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:05Z',
     'local': '2026-09-27 06:05+02:00'},
    'terminal': '1',
    'gate': 'N01',
    'baggageBelt': 'B4',
    'quality': ['Basic', 'Live']},
   'number': 'XQ 966',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'TC-SOR', 'modeS': '4BCDF2', 'model': 'Boeing 737-800'},
   'airline': {'name': 'Sun Express', 'iata': 'XQ', 'icao': 'SXS'}},
  {'departure': {'airport': {'icao': 'LTAU',
     'iata': 'ASR',
     'name': 'Kayseri',
     'countryCode': 'tr',
     'timeZone': 'Europe/Istanbul'},
    'scheduledTime': {'utc': '2026-09-27 01:15Z',
     'local': '2026-09-27 04:15+03:00'},
    'revisedTime': {'utc': '2026-09-27 01:15Z',
     'local': '2026-09-27 04:15+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'terminal': '1',
    'gate': 'X17',
    'baggageBelt': 'A4',
    'quality': ['Basic', 'Live']},
   'number': 'XQ 1716',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'TC-SMF',
    'modeS': '4BCDA6',
    'model': 'Boeing 737 MAX 8'},
   'airline': {'name': 'Sun Express', 'iata': 'XQ', 'icao': 'SXS'}},
  {'departure': {'airport': {'icao': 'ZBAA',
     'iata': 'PEK',
     'name': 'Beijing',
     'countryCode': 'cn',
     'timeZone': 'Asia/Shanghai'},
    'scheduledTime': {'utc': '2026-09-26 18:40Z',
     'local': '2026-09-27 02:40+08:00'},
    'revisedTime': {'utc': '2026-09-26 18:40Z',
     'local': '2026-09-27 02:40+08:00'},
    'terminal': '2',
    'checkInDesk': 'D01-D20',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'terminal': '1',
    'gate': 'Y07',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'HU 489',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A330-300'},
   'airline': {'name': 'Hainan', 'iata': 'HU', 'icao': 'CHH'}},
  {'departure': {'airport': {'icao': 'LZIB',
     'iata': 'BTS',
     'name': 'Bratislava',
     'countryCode': 'sk',
     'timeZone': 'Europe/Bratislava'},
    'scheduledTime': {'utc': '2026-09-27 04:00Z',
     'local': '2026-09-27 06:00+02:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'terminal': '2',
    'gate': 'Z36',
    'baggageBelt': 'C2',
    'quality': ['Basic', 'Live']},
   'number': 'W6 7037',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321 NEO'},
   'airline': {'name': 'Wizz Air', 'iata': 'W6', 'icao': 'WZZ'}},
  {'departure': {'airport': {'icao': 'LROP',
     'iata': 'OTP',
     'name': 'Bucharest',
     'countryCode': 'ro',
     'timeZone': 'Europe/Bucharest'},
    'scheduledTime': {'utc': '2026-09-27 03:00Z',
     'local': '2026-09-27 06:00+03:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'terminal': '2',
    'gate': 'Z34',
    'baggageBelt': 'C1',
    'quality': ['Basic', 'Live']},
   'number': 'W4 3109',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321-200'},
   'airline': {'name': 'Aero Services Executive',
    'iata': 'W4',
    'icao': 'WMT'}},
  {'departure': {'airport': {'icao': 'KEWR',
     'iata': 'EWR',
     'name': 'Newark',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-09-26 21:10Z',
     'local': '2026-09-26 17:10-04:00'},
    'revisedTime': {'utc': '2026-09-26 21:10Z',
     'local': '2026-09-26 17:10-04:00'},
    'runwayTime': {'utc': '2026-09-26 21:30Z',
     'local': '2026-09-26 17:30-04:00'},
    'terminal': 'C',
    'runway': '22R',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:15Z',
     'local': '2026-09-27 07:15+02:00'},
    'runwayTime': {'utc': '2026-09-27 05:08Z',
     'local': '2026-09-27 07:08+02:00'},
    'terminal': '1',
    'gate': 'Y02',
    'baggageBelt': 'B2',
    'quality': ['Basic', 'Live']},
   'number': 'UA 962',
   'callSign': 'UAL962',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 767-400ER'},
   'airline': {'name': 'United', 'iata': 'UA', 'icao': 'UAL'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'VA 6195',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'Virgin Australia', 'iata': 'VA', 'icao': 'VOZ'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'UL 3017',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'SriLankan', 'iata': 'UL', 'icao': 'ALK'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'QR 79',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'Qatar', 'iata': 'QR', 'icao': 'QTR'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'MH 9261',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'Malaysia', 'iata': 'MH', 'icao': 'MAS'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'IB 6386',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'Iberia', 'iata': 'IB', 'icao': 'IBE'}},
  {'departure': {'airport': {'icao': 'OTHH',
     'iata': 'DOH',
     'name': 'Doha',
     'countryCode': 'qa',
     'timeZone': 'Asia/Qatar'},
    'scheduledTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'revisedTime': {'utc': '2026-09-26 23:25Z',
     'local': '2026-09-27 02:25+03:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:25Z',
     'local': '2026-09-27 07:25+02:00'},
    'terminal': '1',
    'gate': 'X01',
    'baggageBelt': 'B3',
    'quality': ['Basic', 'Live']},
   'number': 'FB 1926',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 787-9'},
   'airline': {'name': 'Bulgaria Air', 'iata': 'FB', 'icao': 'LZB'}},
  {'departure': {'airport': {'icao': 'LFSB',
     'iata': 'BSL',
     'name': 'Bâle/Mulhouse',
     'countryCode': 'fr',
     'timeZone': 'Europe/Paris'},
    'scheduledTime': {'utc': '2026-09-27 04:15Z',
     'local': '2026-09-27 06:15+02:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:45Z',
     'local': '2026-09-27 07:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:45Z',
     'local': '2026-09-27 07:45+02:00'},
    'terminal': '1',
    'gate': 'A31',
    'baggageBelt': 'A2',
    'quality': ['Basic', 'Live']},
   'number': 'U2 1187',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320-200 (sharklets)'},
   'airline': {'name': 'easyJet', 'iata': 'U2', 'icao': 'EZY'}},
  {'departure': {'airport': {'icao': 'LFSB',
     'iata': 'BSL',
     'name': 'Bâle/Mulhouse',
     'countryCode': 'fr',
     'timeZone': 'Europe/Paris'},
    'scheduledTime': {'utc': '2026-09-27 04:15Z',
     'local': '2026-09-27 06:15+02:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:45Z',
     'local': '2026-09-27 07:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:45Z',
     'local': '2026-09-27 07:45+02:00'},
    'terminal': '1',
    'gate': 'A31',
    'baggageBelt': 'A2',
    'quality': ['Basic', 'Live']},
   'number': 'DS 1187',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320-200 (sharklets)'},
   'airline': {'name': 'Easyjet Switzerland', 'iata': 'DS', 'icao': 'EZS'}},
  {'departure': {'airport': {'icao': 'KJFK',
     'iata': 'JFK',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-09-26 21:50Z',
     'local': '2026-09-26 17:50-04:00'},
    'terminal': '4',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'X07',
    'baggageBelt': 'A3',
    'quality': ['Basic', 'Live']},
   'number': 'VS 3846',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 767-300 (winglets)'},
   'airline': {'name': 'Virgin Atlantic', 'iata': 'VS', 'icao': 'VIR'}},
  {'departure': {'airport': {'icao': 'KJFK',
     'iata': 'JFK',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-09-26 21:50Z',
     'local': '2026-09-26 17:50-04:00'},
    'terminal': '4',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'X07',
    'baggageBelt': 'A3',
    'quality': ['Basic', 'Live']},
   'number': 'KL 6153',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 767-300 (winglets)'},
   'airline': {'name': 'KLM', 'iata': 'KL', 'icao': 'KLM'}},
  {'departure': {'airport': {'icao': 'KJFK',
     'iata': 'JFK',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-09-26 21:50Z',
     'local': '2026-09-26 17:50-04:00'},
    'terminal': '4',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'X07',
    'baggageBelt': 'A3',
    'quality': ['Basic', 'Live']},
   'number': 'DL 92',
   'callSign': 'DAL92',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N190DN', 'modeS': 'A16883', 'model': 'Boeing 767-300'},
   'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}},
  {'departure': {'airport': {'icao': 'KJFK',
     'iata': 'JFK',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-09-26 21:50Z',
     'local': '2026-09-26 17:50-04:00'},
    'terminal': '4',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'X07',
    'baggageBelt': 'A3',
    'quality': ['Basic', 'Live']},
   'number': 'AF 9085',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 767-300 (winglets)'},
   'airline': {'name': 'Air France', 'iata': 'AF', 'icao': 'AFR'}},
  {'departure': {'airport': {'icao': 'EDDF',
     'iata': 'FRA',
     'name': 'Frankfurt-am-Main',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'terminal': '1',
    'checkInDesk': '259-335',
    'gate': 'A18',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'B10',
    'baggageBelt': 'B2',
    'quality': ['Basic', 'Live']},
   'number': 'NH 6209',
   'status': 'Expected',
   'codeshareStatus': 'IsCodeshared',
   'isCargo': False,
   'aircraft': {'reg': 'D-AILN', 'modeS': '3C658E', 'model': 'Airbus A319'},
   'airline': {'name': 'ANA', 'iata': 'NH', 'icao': 'ANA'}},
  {'departure': {'airport': {'icao': 'EDDF',
     'iata': 'FRA',
     'name': 'Frankfurt-am-Main',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:45Z',
     'local': '2026-09-27 06:45+02:00'},
    'terminal': '1',
    'checkInDesk': '259-335',
    'gate': 'A18',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:55Z',
     'local': '2026-09-27 07:55+02:00'},
    'terminal': '1',
    'gate': 'B10',
    'baggageBelt': 'B2',
    'quality': ['Basic', 'Live']},
   'number': 'LH 172',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AILN', 'modeS': '3C658E', 'model': 'Airbus A319'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'ENGM',
     'iata': 'OSL',
     'name': 'Oslo',
     'countryCode': 'no',
     'timeZone': 'Europe/Oslo'},
    'scheduledTime': {'utc': '2026-09-27 04:25Z',
     'local': '2026-09-27 06:25+02:00'},
    'revisedTime': {'utc': '2026-09-27 04:25Z',
     'local': '2026-09-27 06:25+02:00'},
    'checkInDesk': '4-7',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'revisedTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'terminal': '1',
    'gate': 'B07',
    'baggageBelt': 'B1',
    'quality': ['Basic', 'Live']},
   'number': 'SK 4723',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320 NEO'},
   'airline': {'name': 'SAS', 'iata': 'SK', 'icao': 'SAS'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-09-27 05:00Z',
     'local': '2026-09-27 07:00+02:00'},
    'revisedTime': {'utc': '2026-09-27 05:00Z',
     'local': '2026-09-27 07:00+02:00'},
    'terminal': '2',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'revisedTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'terminal': '1',
    'gate': 'B17',
    'baggageBelt': 'B1',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1928',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320-200 (sharklets)'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'EFHK',
     'iata': 'HEL',
     'name': 'Helsinki',
     'countryCode': 'fi',
     'timeZone': 'Europe/Helsinki'},
    'scheduledTime': {'utc': '2026-09-27 04:05Z',
     'local': '2026-09-27 07:05+03:00'},
    'revisedTime': {'utc': '2026-09-27 04:05Z',
     'local': '2026-09-27 07:05+03:00'},
    'terminal': '2',
    'checkInDesk': 'Area200',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'revisedTime': {'utc': '2026-09-27 06:05Z',
     'local': '2026-09-27 08:05+02:00'},
    'terminal': '1',
    'gate': 'A32',

Data exploration

In [65]:
flights_json.keys()

dict_keys(['arrivals'])

In [66]:
flights_json['arrivals'][0]

{'departure': {'airport': {'icao': 'LTBJ',
   'iata': 'ADB',
   'name': 'İzmir',
   'countryCode': 'tr',
   'timeZone': 'Europe/Istanbul'},
  'scheduledTime': {'utc': '2026-09-27 01:00Z',
   'local': '2026-09-27 04:00+03:00'},
  'revisedTime': {'utc': '2026-09-27 01:00Z',
   'local': '2026-09-27 04:00+03:00'},
  'quality': ['Basic', 'Live']},
 'arrival': {'scheduledTime': {'utc': '2026-09-27 04:05Z',
   'local': '2026-09-27 06:05+02:00'},
  'revisedTime': {'utc': '2026-09-27 04:05Z',
   'local': '2026-09-27 06:05+02:00'},
  'terminal': '1',
  'gate': 'N01',
  'baggageBelt': 'B4',
  'quality': ['Basic', 'Live']},
 'number': 'XQ 966',
 'status': 'Expected',
 'codeshareStatus': 'IsOperator',
 'isCargo': False,
 'aircraft': {'reg': 'TC-SOR', 'modeS': '4BCDF2', 'model': 'Boeing 737-800'},
 'airline': {'name': 'Sun Express', 'iata': 'XQ', 'icao': 'SXS'}}

In [67]:
flights_json['arrivals'][0].keys()

dict_keys(['departure', 'arrival', 'number', 'status', 'codeshareStatus', 'isCargo', 'aircraft', 'airline'])

Looking at the content of the json, the important information is: \
    - flight number \
    - departure airport icao ['airport': 'icao'] \
    - arrival icao \
    - scheduled arrival time, local

#### Creating the flights DataFrame

In [68]:
flights_data = []

for item in flights_json['arrivals']:
    flight_data = {
        'flight_number': item.get('number', None),
        'departure_airport_icao': item['departure']['airport'].get('icao', None),
        'arrival_airport_icao': icao,
        'scheduled_arrival_time': item["arrival"]["scheduledTime"].get("local", None)
    }

    flights_data.append(flight_data)

flight_data_berlin_df = pd.DataFrame(flights_data)
flight_data_berlin_df.head()

,flight_number,departure_airport_icao,arrival_airport_icao,scheduled_arrival_time
0,XQ 966,LTBJ,EDDB,2026-09-27 06:05+02:00
1,XQ 1716,LTAU,EDDB,2026-09-27 06:45+02:00
2,HU 489,ZBAA,EDDB,2026-09-27 06:45+02:00
3,W6 7037,LZIB,EDDB,2026-09-27 07:15+02:00
4,W4 3109,LROP,EDDB,2026-09-27 07:15+02:00

Adjusting the `arrival_time` without the `+02:00`

In [69]:
flight_data_berlin_df["scheduled_arrival_time"] = flight_data_berlin_df["scheduled_arrival_time"].str[:-6]
flight_data_berlin_df.head()

,flight_number,departure_airport_icao,arrival_airport_icao,scheduled_arrival_time
0,XQ 966,LTBJ,EDDB,2026-09-27 06:05
1,XQ 1716,LTAU,EDDB,2026-09-27 06:45
2,HU 489,ZBAA,EDDB,2026-09-27 06:45
3,W6 7037,LZIB,EDDB,2026-09-27 07:15
4,W4 3109,LROP,EDDB,2026-09-27 07:15

#### Creating a function to get flight data from multiple cities

In [70]:
# Creating a function
def gather_flight_datas(icao_list):
    flight_data = []
    api_key = os.environ['RapidFlightAPIKey']
    today_date = datetime.now()
    tomorrow = today_date + timedelta(days=1)
    tomorrow_date = tomorrow.strftime('%Y-%m-%d')

    for icao in icao_list:
        times = [['00:00', '11:59'],    # need two start and end times since the API call can only get max 12 hours of data
                 ['12:00', '23:59']]

    for time in times:
        url = f'https://aerodatabox.p.rapidapi.com/flights/airports/icao/{icao}/{tomorrow_date}T{time[0]}/{tomorrow_date}T{time[1]}'

        querystring = {'withLeg':'true', 
                       'direction':'Arrival', 
                       'withCancelled':'false', 
                       'withCodeshared':'true', 
                       'withCargo':'false', 
                       'withPrivate':'false'
                       }

        headers = {'x-rapidapi-key': os.environ['x-rapidapi-key'],
                   'x-rapidapi-host': os.environ['x-rapidapi-host'],
                   'Content-Type': os.environ['Content-Type']}

        response = requests.request('GET', url, headers = headers, params = querystring)
        flights_json = response.json()

        for item in flights_json['arrivals']:
            flight_item ={'flight_number': item.get('number', None),
                          'departure_airport_icao': item['departure']['airport'].get('icao', None),
                          'arrival_airport_icao': icao,
                          'scheduled_arrival_time': item['arrival']['scheduledTime'].get('local',None)
                          }
        flight_data.append(flight_item)


    flight_data_df = pd.DataFrame(flight_data)
    flight_data_df["scheduled_arrival_time"] = flight_data_df["scheduled_arrival_time"].str.split('+').str[0]



    return flight_data_df

In [71]:
# Get the data from the three cities' airports
icao_list = ["EDDT", "EDDB", "EDDH", "EDDK"] 
gather_flight_datas(icao_list)

,flight_number,departure_airport_icao,arrival_airport_icao,scheduled_arrival_time
0,FR 5519,LEPA,EDDK,2026-09-27 11:55
1,XQ 116,LTAI,EDDK,2026-09-27 23:50

##### Sending the data from the DataFrame to SQL

In [72]:
flights = gather_flight_datas(icao_list)
flights

,flight_number,departure_airport_icao,arrival_airport_icao,scheduled_arrival_time
0,FR 5206,LMML,EDDK,2026-09-27 11:55
1,XQ 116,LTAI,EDDK,2026-09-27 23:50

In [73]:
flights.to_sql('flights',
               if_exists='append',
               con=connection_string,
               index=False)

2